#! /bin/sh
#
# Example panel for lemonbar

. ~/Public/panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		V*)
			volume="%{F#AAAAAA}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{A:bspc monitor -f ${name}:}  %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								wm="${wm}%{A:bspc monitor -f ${name}:} $(printf '%b \ue0f6') %{A}%{B-}%{F-}"
								;;
							F*)
								# focused free desktop
								wm="${wm}%{F#db0a5b}%{A:bspc monitor -f ${name}:} $(printf '%b \ue0f6') %{A}%{B-}%{F-}"
								;;
							o*)
								# occupied desktop
								wm="${wm}%{A:bspc monitor -f ${name}:} $(printf '%b \ue098') %{A}%{B-}%{F-}"
								;;
							O*)
								# focused occupied desktop
								wm="${wm}%{F#db0a5b}%{A:bspc monitor -f ${name}:} $(printf '%b \ue098') %{A}%{B-}%{F-}"
								;;
							u*)
								# urgent desktop
								wm="${wm}%{A:bspc monitor -f ${name}:} $(printf '%b \ue098') %{A}%{B-}%{F-}"
								;;
							U*)
								# focused urgent desktop
								wm="${wm}%{A:bspc monitor -f ${name}:} $(printf '%b \ue098') %{A}%{B-}%{F-}"
								;;
						esac
						wm="${wm}%{A:bspc desktop -f ${name}:}  %{A}%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm}%{c}${title}%{r}${volume}${sys}"
done
